apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../odh-modelmesh-controller/overlays/odh
  - ../odh-model-controller/overlays/odh

namespace: opendatahub
configMapGenerator:
  - envs:
      - params.env
    name: mesh-parameters
generatorOptions:
  disableNameSuffixHash: true


replacements:
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters
    targets:
      - select:
          name: monitoring-namespace
        fieldPaths:
          - metadata.namespace
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters
    targets:
      - select:
          name: monitoring-namespace
        fieldPaths:
          - data.monitoring-namespace
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters
    targets:
      - select:
          name: odh-modelmesh
        fieldPaths:
          - data.odh-modelmesh
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters
    targets:
      - select:
          name: odh-mm-rest-proxy
        fieldPaths:
          - data.odh-mm-rest-proxy
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters
    targets:
      - select:
          name: odh-modelmesh-runtime-adapter
        fieldPaths:
          - data.odh-modelmesh-runtime-adapter
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters
    targets:
    - select:
        name: odh-modelmesh-controller
      fieldPaths:
        - data.odh-modelmesh-controller
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters
    targets:
    - select:
        name: odh-model-controller
      fieldPaths:
        - data.odh-model-controller
  - source:
      kind: ConfigMap
      version: v1
      name: mesh-parameters 
    targets:
      - select:
          name: mesh-parameters
        fieldPaths:
          - data.odh-modelmesh-controller
