apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- envs:
  - params.env
  name: codeflare-stack-config
configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: data.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: codeflare-stack-config

resources:
- ../crd
- ../rbac
- ../manager
- ../prometheus
- ../scc

images:
- name: kuberay/operator
  newName: quay.io/opendatahub/kuberay-operator
  newTag: v0.5.0
