---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./scripts/
  - ./quickstart.yaml
  - ./rbac/
  - ./manager

commonLabels:
  app: model-mesh
  app.kubernetes.io/part-of: model-mesh

configurations:
  - params.yaml
