apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prometheus
- prometheus-operator
- servicemonitors
configMapGenerator:
- envs:
  - params.env
  name: model-monitoring-parameters
configurations:
- params.yaml
vars:
- fieldref:
    fieldPath: data.deployment-namespace
  name: deployment-namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: model-monitoring-parameters
- fieldref:
    fieldPath: data.monitoring-namespace
  name: monitoring-namespace
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: model-monitoring-parameters
